title: Zhengyi's Homepage
author: Zhengyi
email: your-email@example.com
description: 个人主页与博客
baseurl: "" 
url: "https://ustc-zhengyi2023.github.io"
github_username: ustc-zhengyi2023

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: nil
  smart_quotes: [apos, apos, quot, quot]
  entity_output: as_input
  auto_ids: true
  footnote_nr: 1

timezone: Asia/Shanghai
future: true
show_drafts: false
permalink: /posts/:title/

collections:
  posts:
    output: true
    permalink: /posts/:name/
