title: Zhengyi's Homepage
author: Zhengyi
description: 个人主页 | 学习记录 | 技术博客

# GitHub Pages
timezone: Asia/Shanghai
future: true
theme: minima

# Markdown 设置
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# 导航栏链接
header_pages:
  - about.md

# 博客设置
collections:
  posts:
    output: true
    permalink: /posts/:year-:month-:day-:title/

# 分页
paginate: 10
